### ISSUE TITLE
incorrect type for `FileAttachment.contentBytes`

### ISSUE THREAD

**Issue by cjpark** [microsoftgraph/msgraph-typescript-typings#100]
`FileAttachment.contentBytes` should be type `string`, but they're currently typed as `number`

See https://github.com/microsoftgraph/msgraph-typescript-typings/blob/master/microsoft-graph.d.ts#L3846:

```
export interface FileAttachment extends Attachment {
    // The ID of the attachment in the Exchange store.
    contentId?: string;
    // Do not use this property as it is not supported.
    contentLocation?: string;
    // The base64-encoded contents of the file.
    contentBytes?: number;
}
```

**Comment by MIchaelMainer** [comment]
https://issues.oasis-open.org/browse/ODATA-466
https://docs.oasis-open.org/odata/odata/v4.01/csprd06/part1-protocol/odata-v4.01-csprd06-part1-protocol.html#sec_RequestingaPropertysRawValueusingval

**Comment by nikithauc** [comment]
[Issue is currently not there.](https://github.com/microsoftgraph/msgraph-typescript-typings/blob/4f3d0e936f55c80c205f4475e5fd4bfbc9dcf3ab/microsoft-graph.d.ts#L4784)
