### ISSUE TITLE
`Entity` should include odata metadata props

### ISSUE THREAD

**Issue by cjpark** [microsoftgraph/msgraph-typescript-typings#101]
Currently the typings do not include these, so I have to use explicit casts to access the `@odata` props that are coming back in responses (or to include them in request bodies).

Specifically, I'm interested in:
- `@odata.type`
- `@odata.nextLink` (for list calls)
- `@odata.deltaLink` (for delta responses)

as well as any others that may be required

**Comment by MIchaelMainer** [comment]
The sparse applicability of these annotations, and because there can be custom annotations, would make adding all potential instance annotations to Entity not the correct way forward.  

With that said, we have work planned to make it easier to access instance annotations from objects.

**Comment by tyteen4a03** [comment]
Hi @MIchaelMainer , are there any updates to this? Not having this is causing me to need to annotate the typings with the field and it's getting quite cumbersome.
