### ISSUE TITLE
Incorrect type for microsoftgraph.User

### ISSUE THREAD

**Issue by chrisMYchen** [microsoftgraph/msgraph-typescript-typings#124]
The user type does not include createdDateTime while the API returns this field.

See API reference here:
https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0

It might be possible that this should be inherited from the Entity type (which does not have 
 the createdDateTime field either).

**Comment by MIchaelMainer** [comment]
We've put out another release that should address this issue.

https://www.npmjs.com/package/@microsoft/microsoft-graph-types/v/1.13.0
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45833
