### ISSUE TITLE
FieldValueSet type does not match documentation

### ISSUE THREAD

**Issue by BovineEnthusiast** [microsoftgraph/msgraph-typescript-typings#138]
The interface for `FieldValueSet` is defined as follows:

```ts
export interface Entity {
    // Read-only.
    id?: string;
}
export interface FieldValueSet extends Entity {}
```

Meanwhile, in the [example](https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0&tabs=javascript#example) and [resource description](https://docs.microsoft.com/en-us/graph/api/resources/fieldvalueset?view=graph-rest-1.0)
its usage seems to imply that it actually should be defined as follows:

```ts
export interface FieldValueSet {
  [key: string]: any
}
```

If you look at the typed languages (C# or Java) in the example linked above (no typescript example, unfortunately), they use instances of `FieldValueSet` in a way that matches my proposed interface definition.

Should the interface provided in the TypeScript typings be changed?

**Comment by MIchaelMainer** [comment]
FieldValueSet is an opentype where the properties are user defined in SharePoint list items. They cannot be typed ahead of time. The only potentially typed property is ID as specified in Entity.

The interface is correct. You'll need to expect untyped properties on the JavaScript object.

**Comment by Geoffrynagy** [comment]
@MIchaelMainer , the interface is incorrect. The current typing of FieldValueSet only allows 1 optional property "id" and nothing else.
While it should allow any user defined property.
The proposed type of @BovineEnthusiast is more flexible and does exactly that.

When will this error be fixed?
