### ISSUE TITLE
Default @types location request

### ISSUE THREAD

**Issue by inspektor99** [microsoftgraph/msgraph-typescript-typings#140]
Hello, this is a very helpful library. 

I was wondering -- why not put it in the default `node_modules/@types` location typical of installed modules -- with an `index.d.ts`?  This would allow types to be available without adjusting config or importing in source files.

Also this is the suggested behavior in the TypeScript documentation:
https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

Thanks!

**Comment by darrelmiller** [comment]
We also have it deployed to DefinitelyType.  See here https://www.npmjs.com/package/@types/microsoft-graph

**Comment by inspektor99** [comment]
> We also have it deployed to DefinitelyTyped. See here https://www.npmjs.com/package/@types/microsoft-graph

You rock! That worked, thank you! 

You might reference that link in your README, also I noticed your reference uses `microsoftgraph.` instead of the named `MicrosoftGraph` in your README sample.

Thanks again!!
