### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by meme** [microsoftgraph/msgraph-typescript-typings#146]
The last release was tagged ~8 months ago, new changes have been made including:

`AppRoleAssignment`: https://github.com/microsoftgraph/msgraph-typescript-typings/blob/master/microsoft-graph.d.ts#L1491, etc.

I'd rather not pull the module from GitHub locked to `master`, so when is the next release planned in the cycle? Thanks.

(Further [`@microsoft/microsoft-graph-types-beta`](https://www.npmjs.com/package/@microsoft/microsoft-graph-types-beta) doesn't seem to exist, but I thought I'd try that first. Relevant: https://github.com/microsoftgraph/msgraph-typescript-typings/issues/108)

**Comment by ddyett** [comment]
@MIchaelMainer let's discuss getting this update out.

**Comment by meme** [comment]
Relevant: https://github.com/microsoftgraph/msgraph-typescript-typings/pull/147. Changes in the latest TypeScript have now broken your typings.

**Comment by ddyett** [comment]
#147 is now addressed thanks. we will work towards a rollout of this.

**Comment by MIchaelMainer** [comment]
This has been released on DefinatelyTyped and npm.
