### ISSUE TITLE
lastPasswordChangeDateTime missing from User

### ISSUE THREAD

**Issue by rkaw92** [microsoftgraph/msgraph-typescript-typings#150]
Hi,
Apparently, at some point in time, the `lastPasswordChangeDateTime` field has been added to the User type: https://github.com/microsoftgraph/microsoft-graph-docs/pull/6005/files

However, these typings do not reflect this: there is no `lastPasswordChangeDateTime` in the User interface. This makes it troublesome to propagate this data to AAD.

**Comment by zengin** [comment]
This exists in the repository here, but we need to get the typings published in npm and DefinitelyTyped.

**Comment by MIchaelMainer** [comment]
Typings are now updated on definatelytyped and npm.
