### ISSUE TITLE
Wrong type for the key property of the KeyCredential type 

### ISSUE THREAD

**Issue by martinlingstuyl** [microsoftgraph/msgraph-typescript-typings#310]
Hi guys,

I find myself casting the key property of the KeyCredential type all the time.
It is typed as a `NullableOption<number>`, while in practice it's a base64 string.

The description is accurate though:
```typescript
/**
 * The certificate's raw data in byte array converted to Base64 string. Returned only on $select for a single object, that
 * is, GET applications/{applicationId}?$select=keyCredentials or GET
 * servicePrincipals/{servicePrincipalId}?$select=keyCredentials; otherwise, it is always null.
 */
key?: NullableOption<number>;
```

**Comment by zengin** [comment]
Hi @martinlingstuyl, thanks for raising this issue.

According to JSON mapping rules defined [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-odata/b78348e6-44a3-4cc2-87fc-8f852c68f34d), `Edm.Binary` is a base64 string as you described.

Relevant generator code that needs to be fixed:
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/f6866bae964e34039004ac7ef845a90affdc8f0c/src/GraphODataTemplateWriter/CodeHelpers/TypeScript/TypeHelperTypeScript.cs#L35-L36

@rkodev @nikithauc 

cc: @baywet in case we need to double check this in kiota's mapping.

**Comment by nikithauc** [comment]
fixed
