### ISSUE TITLE
Incorrect latest version in npm?

### ISSUE THREAD

**Issue by leeford** [microsoftgraph/msgraph-typescript-typings#336]
Hi All,

I installed this (wonderful) module (via npm) in to a new project and was surprised that the latest version is `3.0.0-RestPreview.1`. I noticed this as a load of typings that have changed from the previous versions.

It looks as if npm is only using this new version as the lastet on this repo is still `2.24.0`.

I just thought I would give a heads up!

**Comment by nikithauc** [comment]
Thank you @leeford for bringing this up. Apologize for any inconvenience caused.

**Comment by leeford** [comment]
No need to apologise. Just thought I would give you a heads up in case this wasn't intentional. 🙂
