### ISSUE TITLE
error TS2304: Cannot find name 'Decimal'. (beta-branch)

### ISSUE THREAD

**Issue by martinvillysson** [microsoftgraph/msgraph-typescript-typings#44]
I just got the following error in our Angular build:
ERROR in node_modules/@microsoft/microsoft-graph-types-beta/microsoft-graph.d.ts(20158,15): error TS2304: Cannot find name 'Decimal'.

I believe the issue is located here: https://github.com/microsoftgraph/msgraph-typescript-typings/blob/beta/microsoft-graph.d.ts#L20158

Seems like it was added by this commit:  https://github.com/microsoftgraph/msgraph-typescript-typings/commit/1b4b132b3cb692f5463c6727c0ae2041efb15672

**Comment by GirishGowda37** [comment]
Getting error while buidling angular 7 by updating npm modules.
Error:
ERROR in node_modules/@microsoft/microsoft-graph-types-beta/microsoft-graph.d.ts(20158,15): error TS2304: Cannot find name 'Decimal'.
Steps: Delete existing . 
In the command line.
npm_modules->npm install->ng serve->error

**Comment by MIchaelMainer** [comment]
This will require an update to the generator to use `number` instead of `decimal`. Let me see about getting that setup so @muthurathinam has something to work with.

**Comment by johnshew** [comment]
Hitting this issue as well.

**Comment by darrelmiller** [comment]
@johnshew The beta Typescript types have been updated.  Let us know if you continue to have issues.

**Comment by johnshew** [comment]
This can be closed.
